export const groups = [
  { name: "Blanda-O'Keefe", id: 1 },
  { name: "Aufderhar-Cronin", id: 2 },
  { name: "Lindgren LLC", id: 3 },
  { name: "Wolff and Sons", id: 4 },
  { name: "Adams Inc", id: 5 },
  { name: "D'Amore and Sons", id: 6 },
  { name: "Schimmel, Wilderman and Orn", id: 7 },
  { name: "Corkery, Reichert and Hodkiewicz", id: 8 },
  { name: "Gorczany Group", id: 9 },
  { name: "Bins Group", id: 10 },
  { name: "Kuhn-Harber", id: 11 },
  { name: "Goodwin-Skiles", id: 12 },
  { name: "Casper Inc", id: 13 },
  { name: "Schoen Inc", id: 14 },
  { name: "Hahn-MacGyver", id: 15 },
  { name: "Steuber, Considine and Padberg", id: 16 },
  { name: "Bogisich and Sons", id: 17 },
  { name: "Metz Group", id: 18 },
  { name: "Bahringer, Auer and Wehner", id: 19 },
  { name: "Hoppe Group", id: 20 },
  { name: "Brekke Group", id: 21 },
  { name: "Durgan Group", id: 22 },
  { name: "Romaguera, Williamson and Kessler", id: 23 },
  { name: "Wintheiser-Boehm", id: 24 },
  { name: "Volkman Group", id: 25 },
  { name: "Boyle, Boyer and Lang", id: 26 },
  { name: "O'Hara and Sons", id: 27 },
  { name: "Leffler, Beatty and Kilback", id: 28 },
  { name: "Bruen and Sons", id: 29 },
  { name: "Balistreri-Kshlerin", id: 30 },
];
